import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'



export default function Home({results}) {

  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
      {/* All these components below gets renderaed on the client side */} 
     {/* Header */} 
     <Header/>
     {/* NavBar */} 
     <Nav />
     {/* Results */} 
     <Results results = {results}/>

    </div>
  )
}
 {/* Server render happens first and then it gets delivered to the client */} 
 {/* All these gets renderaed on the server side */} 
export async function getServerSideProps(context){
  const genre = context.query.genre;

  {/* Making request to TMDb Database */}
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url 
  }`
  ).then((res) => res.json());

  {/* Now returning this data as a Prop to our component*/}

  return {
    props: {
      results: request.results,
    },
  };


}
